{
 "title": "Academy",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Pie %",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "`life-exercise`",
     "rawSql": "SELECT count(*), person_id\nFROM exercise\nGROUP BY person_id"
    }
   ]
  },
  {
   "title": "First date",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "`life-exercise`",
     "rawSql": "SELECT\n  MIN(e.`datetime` ) AS 'last-time',\n  person_id\nFROM\n  exercise e\nWHERE\n  e.`type` = 'ACADEMY'\nGROUP BY\n  person_id;"
    },
    {
     "dataset": "`life-exercise`",
     "rawSql": "SELECT person_id,\nMIN(e.`datetime` ) AS 'data'\nFROM exercise e\nWHERE e.`type` = 'ACADEMY' and e.person_id = '94f28fd8-9abb-425f-a6dc-26910833fa2c'\nGROUP BY person_id;"
    }
   ]
  },
  {
   "title": "Check-ins",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "`life-exercise`",
     "rawSql": "SELECT\n  person_id,\n  COUNT(*) AS 'check-ins'\nFROM\n  exercise e\nWHERE\n  e.`type` = 'ACADEMY'\nGROUP BY\n  person_id;"
    }
   ]
  },
  {
   "title": "Last date",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "dataset": "`life-exercise`",
     "rawSql": "SELECT\n  person_id,\n  MAX(e.`datetime` ) AS 'last-time'\nFROM\n  exercise e\nWHERE\n  e.`type` = 'ACADEMY'\nGROUP BY\n  person_id;"
    }
   ]
  }
 ]
}