apiVersion: 1

datasources:
  - name: Exercise
    type: mysql
    url: mysql:3306
    user: root
    jsonData:
      timezone: '-03:00'
      database: life-exercise
      maxOpenConns: 100 # Grafana v5.4+
      maxIdleConns: 100 # Grafana v5.4+
      maxIdleConnsAuto: true # Grafana v9.5.1+
      connMaxLifetime: 14400 # Grafana v5.4+
    secureJsonData:
      password: 1qazxswedcvfrtgb